# Generated by Django 5.2.4 on 2025-11-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='origin',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
