# Generated by Django 5.2.4 on 2025-11-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shipment_origin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'verbose_name': 'Shipment', 'verbose_name_plural': 'Shipments'},
        ),
        migrations.AlterField(
            model_name='shipment',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
