# Generated by Django 5.2.4 on 2025-11-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_shipment_options_alter_shipment_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='destination',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='origin',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
