# Generated by Django 5.2.4 on 2025-11-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_shipment_destination_alter_shipment_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='destination',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
